### ISSUE TITLE
模型下不了，放百度网盘啊。

### ISSUE THREAD

**Issue by sunjunlishi** [Novelfor/Mandarin_recognition_tf#1]
怎么用啊，看你的效果非常棒啊。

**Comment by Novelfor** [comment]
百度网盘的链接已经添加了，dropbox 的需要翻墙下。
baseline 而已，数据集太小了，而且我没有加任何数据增强。这个数据集的声音特点太明显了，你要用的话最好自己找自己场景的数据重新训下，把数据增强加上。librosa 做数据增强很好用。

**Comment by sunjunlishi** [comment]
你的模型就是普通的 tf模型。你的 声学模型和语言模型怎么组织的呀？

**Comment by Novelfor** [comment]
这是从 DeepSpeech2 的改的一种实现，DeepSpeech 系列的模型都是 end-to-end 的模型，用 CTC 损失函数实现的端到端，和传统的声学模型不一样，https://arxiv.org/abs/1412.5567。
